name: analog-autoformer-supernet

channels:
  - conda-forge

dependencies:
  - python=3.11
  - aihwkit-gpu=1.1.0
  - pip
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - pyyaml
  - easydict
  - scikit-image
  - yacs
  - pip:
      - timm
      - einops
      - opencv-python